---
# shared handlers role. to use it, do:
# tasks:
# - import_role:
#     name: gentoo-services-ctl

# This must go first to preserve order
- name: Reload service definitions
  listen: reload-srv
  systemd:
    daemon_reload: yes

- name: Enable and start systemd services
  listen: ensure-services-started
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  register: start_srv
  failed_when: "start_srv.failed and 'Service is in unknown state' not in start_srv.msg"
  with_items: "{{ systemd_services_safe_restart + systemd_services_unsafe_restart }}"

- name: Reload systemd services
  listen: ensure-services-reloaded
  systemd:
    name: "{{ item }}"
    state: reloaded-or-restarted
  register: start_srv
  failed_when: "start_srv.failed and 'Service is in unknown state' not in start_srv.msg"
  with_items: "{{ systemd_services_safe_restart }}"

- name: Restart systemd services
  listen: ensure-services-reloaded-unsafe
  systemd:
    name: "{{ item }}"
    state: reloaded-or-restarted
  register: start_srv
  failed_when: "start_srv.failed and 'Service is in unknown state' not in start_srv.msg"
  with_items: "{{ systemd_services_safe_restart + systemd_services_unsafe_restart }}"

- name: Reload and apply udev rules from configs
  listen: update-udev-rules
  shell: udevadm control --reload-rules && udevadm trigger
